### PR TITLE
improving setup scripts and kernel files

### PR DESCRIPTION
**Pull request by yymao**
This PR makes several improvement to the setup scripts and kernel files, ordered by the importance:
- add `DESCPYTHONPATH` to the `desc-stack*` kernels
- start ipykernel only if kernel arguments are present (this makes these scripts useful for setting up the same python environments in CLI; cc @wmwv). 
- avoid kernel arguments being propagated to source command (otherwise the unexpected arguments sometimes cause errors or warning messages).
- remove redundant kernel argument (-m) in some of the kernel json files.
- fix a typo (lSST -> LSST) in `desc-pyspark.sh`
- remove an unused script `setup_dev_python.sh` (in the new setting only `setup_current_python` is used. Versioning is done by using different directories).

### CODE REVIEW

**Comment by JulienPeloton** [comment]
@yymao thanks for those changes. In the `desc-pyspark` kernel, could you also update the DESCPYTHONPATH to:

```
export DESCPYTHONPATH="${SPARKPATH}/python/lib/py4j-0.10.7-src.zip:${SPARKPATH}/python:${DESCPYTHONPATH}"
```

such that it is propagated and not reset? (see #4, I just forgot to open the PR).

**Comment by yymao** [comment]
@JulienPeloton done.

**Comment by JulienPeloton** [comment]
Thanks!

**Comment by heather999** [comment]
looks good to me.  I'm ready to approve and merge, then we just need to install this and make sure the kernels are still working as expected.

**Pull request merged**
